camera:
  type:  d-robotics
  intrin:
    fx: 203.239578
    fy: 203.239578
    cx: 259.408417
    cy: 214.265747
    distortion_model: 0
    distortion_coeffs:
      []
  extrin:
    -
      - 0.0291321669
      - 0.00556206144
      - 0.999560118
      - -0.0102712447
    -
      - -0.999529362
      - -0.00944640022
      - 0.0291838404
      - 0.0456708223
    -
      - 0.00960456673
      - -0.999939919
      - 0.00528425025
      - -0.00414995197
    -
      - 0
      - 0
      - 0
      - 1
  pitch_compensation: 0
  yaw_compensation: 0
  z_compensation: 0
detection_model:
  model_path: ./src/vision/model/k1_realsense_0120.engine
  confidence_threshold: 0.2
  nms_threshold: 0.4
  classnames: [Ball, Goalpost, Person, LCross, TCross, XCross, PenaltyPoint, Opponent, BRMarker]
  post_process:
    single_ball_assumption: false
    confidence_thresholds:
      Ball: 0.4
      Goalpost: 0.4
      Person: 0.4
      LCross: 0.3
      TCross: 0.3
      XCross: 0.3
      PenaltyPoint: 0.3
      Opponent: 0.4
      BRMarker: 0.2
segmentation_model:
  model_path: ./src/vision/model/best_seg_orin_10.3.engine
  confidence_threshold: 0.3
  nms_threshold: 0.9
use_depth: true
ball_pose_estimator:
  use_depth: false
  radius: 0.091
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
  minimum_cluster_size: 150
  filter_distance: 1.2
  check_ball_height: true
human_like_pose_estimator:
  use_depth: false
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
field_marker_pose_estimator:
  refine: false
  line_segment_area_threshold: 75
calibration:
  sync_max_time_diff_ms: 1400
  offset:
    exclude_distance: 2.0
    zero_translation: true
    field_marker_path: ./src/vision/config/field.yaml
  handeye:
    calibration_time: 2026-09-23-14-32-34
    reprojection_error: 3.6635394527953244
misc:
  save_data_nonstationary: true